import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Baric",
      email: "admin@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "John",
      email: "user@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: "1",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.2,
      numReviews: 10,
      description: "high quality product",
    },
    {
      // _id: "2",
      name: "Lacrosse Free Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 220,
      countInStock: 20,
      brand: "Nike",
      rating: 3.6,
      numReviews: 17,
      description: "high quality product",
    },
    {
      // _id: "3",
      name: "Alice Free Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 0,
      brand: "Nike",
      rating: 4.7,
      numReviews: 10,
      description: "high quality product",
    },
    {
      // _id: "4",
      name: "Nike Slim Pant",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 78,
      countInStock: 15,
      brand: "Nike",
      rating: 3.7,
      numReviews: 14,
      description: "high quality product",
    },
    {
      // _id: "5",
      name: "Puma Slim Pant",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 75,
      countInStock: 5,
      brand: "Puma",
      rating: 4.2,
      numReviews: 10,
      description: "high quality product",
    },
    {
      // _id: "6",
      name: "Adidas Ftt Pant",
      category: "Pants",
      image: "/images/p6.jpg",
      price: 139,
      countInStock: 5,
      countInStock: 12,
      brand: "Adidas",
      rating: 2.9,
      numReviews: 19,
      description: "high quality product",
    },
  ],
};

export default data;
