const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Lacrosse Free Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 220,
      brand: "Nike",
      rating: 4.6,
      numReviews: 17,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Nike Slim Pant",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 78,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Puma Slim Pant",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 75,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Adidas Ftt Pant",
      category: "Pants",
      image: "/images/p6.jpg",
      price: 139,
      brand: "Adidas",
      rating: 4.9,
      numReviews: 19,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: "120",
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};

export default data;